syntax = "proto3";

package control;

option go_package = "diplom_code/api/controlpb";

service ControlService {
  rpc StartScenario(StartScenarioRequest) returns (StartScenarioResponse);
  rpc StopScenario(StopScenarioRequest) returns (StopScenarioResponse);
  rpc GetStatus(StatusRequest) returns (StatusResponse);
  rpc StreamStatus(StreamStatusRequest) returns (stream StatusEvent);
}

message StartScenarioRequest {
  string scenario_json = 1;
}

message StartScenarioResponse {
  string run_id = 1;
  string message = 2;
}

message StopScenarioRequest {
  string run_id = 1;
}

message StopScenarioResponse {
  string run_id = 1;
  string message = 2;
}

message StatusRequest {
  string run_id = 1;
}

message StatusResponse {
  string run_id = 1;
  string state = 2;
  string message = 3;
}

message StreamStatusRequest {
  string run_id = 1;
}

message StatusEvent {
  string run_id = 1;
  string state = 2;
  string details = 3;
  int64 unix_time = 4;
}
